### ISSUE TITLE
Handheld Map options

### ISSUE THREAD

**Issue by Qugar** [Miloet/LC_Map#1]
Would it perhaps be possible to add an option so that only loot is displayed on the map? No turrets, no doors and no enemies?

Great mod so far just a bit powerful =)

**Comment by Miloet** [comment]
it all depends on how the game creator, zeekers, has layered everything. if
each map object, I.E turrets, doors, enemies, loot, and ground(maybe) are
layered separately it should be fairly easy. Otherwise quite difficult. I
will have a look.

**Comment by Qugar** [comment]
Maybe there are some really good approaches in this mod? Apparently it is possible to turn various things on and off there.

I don't want this to come off the wrong way. I'm just trying to be helpful. An item with these functions and battery consumption would be simply great.

[https://thunderstore.io/c/lethal-company/p/Tyzeron/Minimap/](url)

**Comment by Miloet** [comment]
I’ll check it out. thanks for the input!

tors 8 feb. 2024 kl. 00:37 skrev Qugar ***@***.***>:

**Comment by Miloet** [comment]
i used the mod you gave as a base for how to do it for my mod. it has now
been implemented. i do expect some bugs to exist but for the most part it
works!

**Comment by Qugar** [comment]
I found two problems.

1. If you switch the map in the ship to another player, the tool also shows that player instead of itself.

2. I don't know exactly what happens, but as soon as you get to the map on the ship, the configs for the tool are overwritten.

I know that there was a minimap where you could have this minimap separate from the map in the terminal. Unfortunately it wasn't a tool to take with you but was simply displayed in the hud. I'll see if I can find it again and then edit the post.

But great progress so far and thank you for looking at it and trying to make it happen.

Edit:
This isn't exactly the minimap I meant, but in both of these mods there seems to be a way to create a new instance that is independent of the map on the ship.

[https://thunderstore.io/c/lethal-company/p/Zaggy1024/TwoRadarMaps/](url)
[https://thunderstore.io/c/lethal-company/p/SeparateCameras/SeparateCameras/](url)

Please excuse all the trouble.

**Comment by Miloet** [comment]
The second point is intentional. when the player is inside the ship all map objects are shown as normal, allowing for the navigator to still do their job by seeing all the mapobjects. when the player leaves the ship the map objects are changed to reflect the settings. also this is no trouble at all, i love having the bugs told to me since i have limited testing capabilities. this instance is independent from the ship in most regards but since it largely uses the monitors original code some cracks slip through. will look into and fix

**Comment by Qugar** [comment]
If the second point is intentional, then it could be that the first point only takes place on the ship.
Unfortunately I don't know when I'll be able to play multiplayer in the next few days.
I will give you further feedback, of course even more so if everything works.

Edit: Is it possible to hide turrets as well?

**Comment by Miloet** [comment]
i did add that just forgot to add it to the config file, not 100% sure if it works just yet tho. i also fixed switching issue- tho the green flash animation is still synced between them and idk how to fix that since its basically a server call telling it to play.

**Comment by Qugar** [comment]
Unfortunately, turrets and mines are displayed to me if I set it to false in the config.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/eb164a7c-d0da-4a6b-9dc4-cd706dc4951f)
![grafik](https://github.com/Miloet/LC_Map/assets/8191849/398972c2-e2e8-4ee7-9375-601725e6adb5)

And I don't know why but this eyeless dog was shown to me. I can't reproduce why it's displayed to me either.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/2bb9d92e-1ee0-44b9-b777-2756f10dcb3c)

Yes, I died but I needed the picture. XD

If it's just the green flash animation then that's completely ok at least for me.

Here are a few mods with which handheld map is compatible, which I thought could have caused problems but it works without any errors:

AdvancedCompany
LethalLevelLoader
Modded moons
Modded enemies

Edit: After going back to the main menu and then starting again, the handheld map disappears from the ship. Found the handheld map outside the ship, apparently the position is not saved correctly when you leave the save file.

Edit2: So first the good news. I was just able to test the tool in multiplayer and the errors that occur there are the same as in singleplayer. The multiplayer seems to work great with the tool.

However, sometimes the enemies appear on the tool and I just can't reproduce it reliably.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/3978fba0-4cff-4ef1-bbc5-4691793b3186)
![grafik](https://github.com/Miloet/LC_Map/assets/8191849/a18ba0a2-97a2-44d2-8734-e52e374dedf0)

As you can see in the picture, the opponent disappears from the map again. That's why I'm wondering whether the game sends updates from the ship map or whether there is an update rate for the tool.

Then I found two rather small, not so important errors.

1. In the config you wrote scarp instead of scrap, nothing crazy.
2. Lamps are not shown as loot but only the light source, not that bad either.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/5fdd7722-d67c-4e77-8c26-f5a9881d20fa)

To keep a bit of an overview:
1. Turrets and mines are displayed despite the config. If it can't be solved, it's not a problem.
2. Sometimes enemies are displayed on the tool.
3. The green flash animation. But it's not a bad thing if you don't find a solution.
4. When loading the save file, the tool is outside the ship.
5. Lamps are shown as light source and not as loot, would be ok.
6. In the config Scarp as a typo.

But all in all it looks very good and I already love it. The biggest error would be that enemies sometimes appear even when you are not at the ship.

Thank you so far. :smile:

**Comment by Miloet** [comment]
For the turrets and the mines i used a very bad temp solution that didn't work. It has now been changed and i will test it shortly. 
The eyeless dog being visible might have been because you were semi-close to the ship (within 10 units of it) but the snare flee in the facility i am a bit more unsure of- it could be that when new enemies spawn it doesn't change it for them, that might have been the case with the dog as well. 
The savefile loading i believe i know a fix to as well. 
I fixed the scarp typo 🤚💀

Thank you for all your work as well. 

Edit:
yes there is a 5 second update rate for the tool but it should be an issue unless you leave the ship and come back or use the jetpack to get to the facility. I can lower it an see the results.

**Comment by Qugar** [comment]
First of all, I'm happy to be able to help.

The update rate could perhaps be built into the config, then I could immediately test how much impact it has on performance and the players can decide for themselves, depending on their system, which rate they think is appropriate.
Maybe with a small note that it can affect performance and that no values ​​less than one second should be selected, that would be a good option. It's just an idea.

Regarding the eyeless dog, I don't know what 10 units are, but on Atlas Abyss the spot was about as far away as the distance on Experimentation to the ladder.
But as I said, all in all there's actually only one thing left that needs to be fixed, the rest are all more like cosmetic flaws that aren't too wild.

My group is also really excited about the mod and on Monday it will probably be tested over a longer period of time and with even more people.

**Comment by Miloet** [comment]
I have added the update rate as a config. 
Did the enemy visibility happen during a longer period of time like 10 seconds? Or did it always eventually switch off?

**Comment by Qugar** [comment]
So far I've always walked away from the enemies and checked to see if they were still visible when I came back. I'll stay with the enemy the next time it occurs.

**Comment by Miloet** [comment]
I checked and changed the code a bit. I tested it with 20 hoarding bugs and used the jetpack, non where visible by the time i got there. There is still the problem of enemies showing up right after they spawn but that would take quite a bit of code to fix. plus its only for the next update cycle.

**Comment by Qugar** [comment]
This just happened. If I stick with the visible enemies, then they won't fade out over time and every enemiy that comes along will also be visible.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/b47bf726-b05b-4092-8968-b95e5bcfdaf8)

Was created over a period of 2-3 minutes.

I'll see what happens with the new version as soon as r2modman recognizes it.

Edit: I will also test if it is a compatibility issue with other mods. This could take a while.

Edit2: So far it looks good. The fact that the enemies are shown briefly when spawning shouldn't be a problem as you can notice it yourself in most cases.

Also couldn't find any compatibility issues with my other mods, which is very good.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/a69a1b8e-1195-4d00-940e-7623ca354393)

Is the last “Scarp” entry intentional? :joy:

Mines are no longer displayed, I still have to look for turrets, I will test it a little more and then give you feedback again, but so far it looks very promising.

A small request actually came up earlier in multiplayer. If you collect scrap, then the tool logically switches off. Switching it on costs battery every time if it is not set to 0, which makes sense. I was asked if I could ask if something could be done, I'm guessing not but I thought I'd throw it out there.

**Comment by Miloet** [comment]
the last one is because i changed the name- you can remove it in the .config file and it should be good. Do you mean like a setting so that it doenst turn off when you unequip it / pick up loot?

**Comment by Qugar** [comment]
Oh sure, sorry, my mistake.

Preventing it from turning off would be great, but I suspect it's either not possible or time-consuming.
Preventing switching slots would probably cause compatibility problems because there are mods that work with switching slots.

I've now tried it with an update rate of 1 and can't notice any loss in performance.
Also, I haven't seen a single enemy on the handheld map anymore, even when they spawn. Of course that could be a coincidence, but so far it looks perfect, I just have to look for turrets, they just don't spawn right now.

Edit: Is the update rate function carried out individually for each tool or does each tool receive the update via a single command? I only ask because the former could lead to a strong performance impact if many players use many tools at the same time.

Edit2: It now works great in singleplayer and turrets are no longer displayed. With the update rate of 1 I don't even see spawning enemies.

I will test it in multiplayer as soon as possible and give you feedback again.

But I would like to thank you in advance for your patience and for the implementation. This mod is an asset to us and you are definitely a great great asset to the modding community. :smirk:

**Comment by Miloet** [comment]
Thank you! 
The switching is really easy to implement actually so I will do that real quick.

**Comment by Qugar** [comment]
Works well and once again you have exceeded my expectations. Thank you.

**Comment by Miloet** [comment]
:> 👍

**Comment by Qugar** [comment]
As promised, the feedback on the mod in multiplayer:

Everything worked out wonderfully, no errors or anything and the people are very happy.
With the exception of one person who would like the minimap to be displayed small in the hud when you have the tool on and put away.

I said that I could ask if that would be possible, but I also mentioned that that wasn't actually the intention behind the mod, because otherwise we could have used another mod.

In any case, I thank you very much again, apart from the small thing that the tool flies on some maps when you order it, there have been absolutely no problems.

**Comment by Miloet** [comment]
Yeah, that kinda goes against the intentions. I wanted to make a mod that fits in and mimics Lethal Company's items (and adding it would take quite a long time). I have no clue what causes it to do that tbh.

Currently I am trying to "stupid proof" the mod so that it will work no matter the mods that are used- well to a certain degree anyways.

**Comment by Qugar** [comment]
Completely understandable and as I said, I also think it's nonsense, because otherwise we could have chosen another mod, it was important to me that there wasn't a mini map in the hud.

But as I said, that was just one person and I think you can never make everyone happy. The majority of people are happy and so am I because you really took a lot of time for it.

Great work and keep it up. :smile::thumbsup:

**Comment by Miloet** [comment]
I wanna thank you. You have been an invaluable resource in making this mod better. Both in the feedback and bug-catching you have done but also from a motivational standpoint. I can often find it hard to keep on going when I hit my head against a brick wall for hours on end but knowing someone is standing in my corner hoping I succeed is just such a boost to that. 
This was just a hobby project, turned school later on, and I finally feel like I can say this mod is good. Mostly thanks to you and everyone else who has contacted me about bugs and such. 

Thank you, truly.

**Comment by Qugar** [comment]
I was happy to help and yes it definitely turned out to be a good mod. I'm very pleased that you can take such a sense of achievement with you from all the work you've done and you can also be very proud of yourself.

I had always thought about whether I would find a mod like this and you realized what I was looking for. It's a bit sad that it's finished now because I also had a lot of fun giving you feedback and seeing how you continued to develop the mod.

Thank you for your perseverance.

**Comment by Qugar** [comment]
Hi,

It's me again. I actually found a small error but I'm sure you'll get it fixed relatively quickly and without any problems.

The way the mod is at the moment, the tool updates as soon as you have it in your inventory, which may lead to severe performance losses. I had tools with me for the whole team and my frames dropped to 20 fps.

I then looked at the whole thing in the logs and in fact every tool updates as soon as it is in the inventory, if I saw it correctly the tool does not update if it is on the floor even if it is on, which is perfect. If you could also implement this so that only the tool you are actively holding in your hand updates, the problem should be solved.

**Comment by Miloet** [comment]
You’re right about it being easy. I’ll add a check to see if it is the
local player holding it and if it isnt it wont update. That should ensure
that it never updates when you specifically dont hold it. I could see if
there is any varibles such as ”pocketed” or ”in hand” so that it only
updates when youre looking at it and not while its pocketed. I’ll have it
fixed within 24 hours.

tis 13 feb. 2024 kl. 07:16 skrev Qugar ***@***.***>:

**Comment by Qugar** [comment]
Thank you.

I can always count on you. 😄

**Comment by Miloet** [comment]
I tried to make it so that you could have settings for update distance, max amount of maps and if you should be able to view other players maps at all. But I couldnt manage to get it to work
In earlier versions I remember you could view other players maps as well but it seams that I broke that in some update along the way. 
I did do the preformance update so things should be stable frame wise. Both the map object culling and the map camera updates have been locked to only the local client player.

**Comment by Qugar** [comment]
Unfortunately that didn't solve the problem. I used ten tools for testing purposes and my frames went below 14 FPS. As soon as I throw away the tools it goes back to normal.

Are the tools rendered and calculated as soon as I have them in my inventory? Maybe invisible? Something is happening in the background.

**Comment by Miloet** [comment]
well it should fix it for when other people are using them. it could be that the "isHeld" variable is actually for when its in your inventory rather than in your hand. ill do some quick testing

edit: that sure was it. will try to find, or create if i have to, a variable that will be for if its in the hand.

**Comment by Qugar** [comment]
Another little thing is that if you turn the tool on and off quickly you get negative battery values.

I think this should be solveable with a query as to whether the battery value is less than 0 then equal to 0.

Should then also fix problems with mods that only cause partial charging through objects.

**Comment by Miloet** [comment]
The only reason i didnt add that is cuz i thought zeeker already had done that for chargable items... guess not! or well i do it slightly differently- ill fix it.

**Comment by Qugar** [comment]
I'm sorry for causing you trouble again. :sweat_smile:

It's all the little things that you can overlook or don't notice because you don't think anyone could do that.

**Comment by Miloet** [comment]
No need to say sorry. Thank you for your valuable input.

**Comment by Qugar** [comment]
Now the background of the tool turns green but no map can be seen anymore. :anguished:

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/3049fe52-1297-4f0b-b638-fcb32e833f83)

Or if you turn on the map on the ship, it no longer updates when you leave the ship.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/aa303e66-07f4-4bcd-b7d8-75706d985032)

It almost seems as if it now only synchronizes with the map on the ship, which is not active when no one is on the ship. At least not with the mods we use.

**Comment by Miloet** [comment]
Very strange... ill have a look soon. i am pretty sure i didnt change anything that would cause this...

**Comment by Miloet** [comment]
ok so i think i figured out what is causing the lack of updating. the logic for when it should update might have been flawed in how it checked. but there is a second issue in that provided picture i believe. i added a fail safe a few patches ago which used a camera that was close but not exactly the one used in game as a replacement if it couldnt find it. it has different layers so it looks a bit more "high detail" than the normal map. did you get any errors in a little yellow box to the right connected to this mod?

**Comment by Qugar** [comment]
No, I didn't, but if you're confused by the look of the map, that could be because it's on Triskelion, where everything outside the facility is made of grid paths.

**Comment by Miloet** [comment]
Oooooooohhh (thank god cuz otherwise it be would be a lot harder to solve. I just released a patch. It works fine for me. I realized another performance update too that will make being in the ship with many maps much better. I hope it fixes it

**Comment by Qugar** [comment]
I will download it manually to give you quicker feedback.

Edit:
First, this is what the floor of Triskelion looks like.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/2e95adf2-b179-46b8-bcd7-48af92df02ee)

And no, unfortunately the problem is not solved for me. :worried:

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/2a1c56ae-545a-4425-ba0a-88804bdfb00d)

I'll see if BepInEx outputs anything.

Edit2:
BepInEx doesn't give me any errors. However, I just noticed that when I switch the tool on and off in the ship, there is the green flash animation on the map monitor. I don't think this happened in version 1.5 when it still worked.

**Comment by Qugar** [comment]
I created a completely new profile using only BepInEx and your mod, unfortunately the result remains the same.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/a32c6c0a-43a4-4ff5-8921-646d96c20f5e)

**Comment by Miloet** [comment]
I did find an error in BepInEx. I will try to find the solution.

**Comment by Qugar** [comment]
Now I feel really bad about how much trouble this is causing.

**Comment by Miloet** [comment]
No no, its fine. I figured out which piece of code was causing it. 

Edit: i think i found and fixed the problem.

**Comment by Miloet** [comment]
ok 1.5.4 is out now. you can download and check it out.

**Comment by Qugar** [comment]
I don't dare say it, but nothing has changed.

**Comment by Miloet** [comment]
![Screenshot (1060)](https://github.com/Miloet/LC_Map/assets/62662716/4f144ce8-fd3d-4b89-ad0c-ff01bb15b700)
One step closer. I managed to recreate it.

**Comment by Qugar** [comment]
How is it possible that we get such different results when I am on a newly generated profile?

Am I doing something wrong? :cold_sweat:

Forgive me for the stupid questions, my knowledge is limited to php and Lua. :sweat_smile:

**Comment by Miloet** [comment]
I believe I might have forgotten some kind of dependency. 

Edit: ... it works when i add lethalthings...

Edit2: wait wait wait I FIGURED IT OUT! it turns off the camera for some stupid reason :P

**Comment by Miloet** [comment]
fixed it :3

**Comment by Qugar** [comment]
Do I need lethalthings now? Because without it, unfortunately it still doesn't work. And with I just had everything displayed turrets, mines, and so on despite the config.

Edit: It works on the ship but it doesn't work outside the ship. In any case, it's another step in the right direction.

**Comment by Miloet** [comment]
I fixed it by removing a redundant optimization. Just make sure to not activate multiple maps in your inventory at the same time.

**Comment by Qugar** [comment]
I'll take a look at it later, I've got a bit of work to do at the moment.

You have set the tool to turn off when you put it away and then put a setting in to prevent that, right?

I'm only asking because I'm wondering whether you can use a similar method to check whether a map in the inventory is on before switching on a map and then switch it off if necessary.

If I understood correctly, is.held checks the entire inventory, right?

I'm just imagining, with my layman's knowledge, that you can perhaps do a check beforehand via is.held. After checking and switching off the maps, could you possibly switch on the map in your hand?

**Comment by Miloet** [comment]
You’re onto something with using the same method as the setting. I’ll
implement it when I have time later today.

**Comment by Qugar** [comment]
First of all it works again.

However, the frames continue to drop. It has gotten better but is still there and noticeable from 3-4 tools onwards. But as before, only if they are in your own inventory.

Is there any function in the mod that checks is.held again and again?
Does each tool have its own map or is there one map for each player?
Whatever it is, the query or the rendering of the map or whatever, should only happen when the player is actively holding the tool in his hand, and ideally only when the tool is turned on.

Tack för din insats.

Edit:
By the way, I don't want to say that your mod necessarily has a bug. It is also possible that Zeekerss has errors in the code and your mod is now struggling with them.
However, there is certainly a solution and if there is, I believe you will find it. :wink:

**Comment by Miloet** [comment]
I can easily fix the multible in inventory maps problem as i have a good
fix for it. I’ll add that it only updates when on (i think it might already
do that but better to be safe)
Each map has a camera but they only render when in inventory (and soon only
when in hand and active) and i could do a small rewrite of a part of the
code to make it be a single one only following the local player. I could
otherwise add that the cameras are deactive when not used making it so the
fps goes up and making only one camera is just a small memory issue instead
of an fps issue.

First of all it works again.

**Comment by Qugar** [comment]
That all sounds good, I'm definitely looking forward to it.
Little by little your mod will get even better.

**Comment by Qugar** [comment]
Hi,

I just saw your new update and you seem to have fixed all the errors. Even if I turn on all maps in the inventory, it no longer affects performance at all.

You did a great job again.
Very big thank you.

**Comment by Miloet** [comment]
:> 👍

**Comment by Qugar** [comment]
Hi, unfortunately the map now turns off again when you switch the slot or pick up an item. I have the option set to false in the configs.

![grafik](https://github.com/Miloet/LC_Map/assets/8191849/4c2ee993-95d7-435d-9c2a-cf525c4a729a)

**Comment by Miloet** [comment]
Ill look into it!

Yeah i found the problem and fixed it. 
I forgot to add that the setting has an effect thanks to me reworking it so the settings update in real time.

**Comment by Miloet** [comment]
![dfrgtyhujiko](https://github.com/Miloet/LC_Map/assets/62662716/6001d26e-60e2-48c2-8937-806ac751c22d)
this in specific was the problem. the line wasnt there before-

**Comment by Qugar** [comment]
Great, we can rely on you. :smiley:

**Comment by Qugar** [comment]
Everything works again, thank you, you're the best. 😃
